import type { Metadata } from 'next';
import '../style/reset.scss';
import RecoilRootWrapper from './RecoilRootWrapper';
import LayoutProvider from './LayoutProvider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body>
                <RecoilRootWrapper>
                    <LayoutProvider>{children}</LayoutProvider>
                </RecoilRootWrapper>
            </body>
        </html>
    );
}
